HavenRoute/urls.py
from django.contrib import admin
from django.urls import path, include
from HavenRouteApp import views
from django.views.generic import TemplateView
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html'), name='index'),
    path('ports/', views.PortListView.as_view(), name='Port_List'),
    path('add_port/', views.AddPortsView.as_view(), name='Add_Port'),
    path('add_amenity/', views.AddAmenityView.as_view(), name='Add_Amenity'),
    path('amenities/', views.AmenitiesListView.as_view(), name='Amenities'),
    path('cruise/', views.CruiseView.as_view(), name='Cruise'),
    path('create_route/', views.CreateRouteView.as_view(), name='Create_Route'),
    path('add_route_port', views.AddPortRouteView.as_view(), name='add_port_route'),
    path('routes', views.RouteView.as_view(), name='routes'),
    path('add_cruise', views.AddCruiseView.as_view(), name='add_cruise'),
    path('port/<int:pk>/', views.PortDetailView.as_view(), name='port_detail'),
    path('update_port/<int:pk>', views.PortUpdateView.as_view(), name='update_port'),
    path('cruise/<int:pk>/', views.CruiseDetailView.as_view(), name='cruise_detail'),
    path('route/<int:pk>/', views.RouteDetailView.as_view(), name='route_detail'),
    path('accounts/', include('accounts.urls')),

]

accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('create_user/', views.RegisterView.as_view(), name='add_user')
]

HavenRouteApp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Amenity(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Port(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(default='')
    lattitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    amenities = models.ManyToManyField(Amenity, blank=True)

class Route(models.Model):
    name = models.CharField(max_length=128, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stop_list = models.ManyToManyField(Port, through='RoutePort')


class RoutePort(models.Model):
    port = models.ForeignKey(Port, on_delete=models.CASCADE)
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()


class Cruise(models.Model):
    name = models.CharField(max_length=128)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(auto_now_add=True)
    route = models.ForeignKey(Route, on_delete=models.CASCADE, null=True)
    crew = models.ManyToManyField(User, related_name='crew')

templates/Amenity_List.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul class="list-group">
        {% for amenities in amenity_list %}
            <li class="list-group-item">{{ amenities.name }}</li>
        {% endfor %}
    </ul>
</body>
</html>
{%  endblock %}

templates/Cruise_View.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
</tr>
    {% for cruise in cruise_list %}
        <tr class="{% cycle 'bg-secondary' 'bg-light' %}">
        <td>{{ forloop.counter }}</td>
        <td>{{ cruise.name }}</td>
        <td><a href="{{ port.get_absolute_url }}">zmien</a> </td>
        <td>
            <form action="{% url 'cruise_detail' cruise.id %}" method="get"> {% csrf_token %}
                <input type="submit"></form>
        </td>

    </tr>
    {% endfor %}
    </ul>
</body>
</html>
{%  endblock %}

templates/Port_List.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <tr>
        <th>Lp</th>
        <th>Nazwa</th><br>
    </tr>
    {% for port in port_list %}
        <tr class="{% cycle 'bg-secondary' 'bg-light' %}">
        <td>{{ forloop.counter }}</td>
        <td>{{ port.name }}</td>
        <td>
            <form action="{% url 'port_detail' port.id %}" method="get"> {% csrf_token %}
                <input type="submit">Opis Portu</form>
        </td>
        <td>
            <form action="{% url 'update_port' port.id %}" method="get"> {% csrf_token %}
                <input type="submit">Uaktualnij</form>
        </td>


    </tr>
    {% endfor %}
</body>
</html>
{% endblock %}

templates/RouteView.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <tr>
        <th>Lp</th>
        <th>Nazwa</th>
    </tr>
        {% for route in route_list %}
            <tr class="{% cycle 'bg-secondary' 'bg-light' %}">
            <td>{{ forloop.counter }}</td>
            <td>{{ route.name }}</td>
            <td><a href="{{ route.get_absolute_url }}">zmien</a> </td>
            <td>
                <form action="{% url 'route_detail' route.id %}" method="get"> {% csrf_token %}
                <input type="submit"></form>
            </td>
    </tr>
    {% endfor %}
    </ul>
</body>
</html>
{% endblock %}

templates/add_object.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

templates/base.html
{% load static %}
{% include 'header.html' %}
<body>
{% include 'top_navbar.html' %}
<div class="m-3">
{% block content %}
{% endblock %}
</div>
<script src="{% static 'bootstrap-5.2.0-dist/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/create_route.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{%  endblock %}

templates/form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

templates/header.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="{% static 'bootstrap-5.2.0-dist/css/bootstrap.css' %}" rel="stylesheet">
</head>

templates/links.html
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Index</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Port_List' %}">Lista portów</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'routes' %}">Trasy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Add_Port' %}">Dodaj Port</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Add_Amenity' %}">Dodaj udogodnienia</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Amenities' %}">Udogodnienia</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Cruise' %}">Rejs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_cruise' %}">Dodaj Rejs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Create_Route' %}">Stwórz trasę</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'add_port_route' %}">Dodaj przystanek</a>
        </li>

    </ul>
</div>